Repository robogyan-adgitm/robogyan-adgitm.github.io, pull requests merged in 2022-10, with the labels that each got.

#2 Create README.md
  README.md
Labels: hacktoberfest-accepted

#1 add meta tags
  index.html
Labels: hacktoberfest-accepted

#8 landing page
  index.html
  style.css
Labels: hacktoberfest-accepted

#13 correct typos
  index.html
Labels: hacktoberfest-accepted

#14 Apply link added
  index.html
Labels: hacktoberfest-accepted

#15 Background-responsiveness
  background.jfif
  newbackground.jpg
  style.css
Labels: hacktoberfest-accepted

#19 animation added and text improved
  index.html
  style.css
Labels: hacktoberfest-accepted, hacktoberfest

#18 Created contribute.md
  Contribute.md
Labels: hacktoberfest-accepted, hacktoberfest

#20 added info about reducing spam
  Contribute.md
Labels: hacktoberfest-accepted

#21 Formatting in Contribute.md
  Contribute.md
Labels: hacktoberfest-accepted, hacktoberfest

#22 added mailing address
  index.html
Labels: hacktoberfest-accepted

#23 added link to social media
  index.html
Labels: hacktoberfest-accepted

#29 Added Animated hamburger
  index.html
  style.css
Labels: hacktoberfest-accepted

#31 Sm8uti dev
  assets/logo-r.svg
  assets/logo.svg
  assets/user-add.svg
  background.jfif
  dist/css/main.css
  dist/css/main.css.map
  dist/css/main.scss
  dist/js/main.js
  index.html
  newbackground.jpg
Labels: hacktoberfest-accepted

#32 Added links in nav bar of new site
  index.html
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#33 updated README
  README.md
Labels: hacktoberfest-accepted

#34 added contributors list
  contributors/contributorsList.js
Labels: hacktoberfest-accepted

#38 added href
  about.html
  index.html
Labels: hacktoberfest-accepted

#39 changes in readme
  README.md
Labels: hacktoberfest-accepted

#44 Added a accordion for Showing FAQs. Answers are shown in the collapsable drawer as mentioned.
  dist/css/main.css
  faq.css
  faq.html
Labels: hacktoberfest-accepted

#42 Added hover to navbar
  dist/css/main.css
Labels: hacktoberfest-accepted

#55 Updated Footer UI
  about.html
  dist/css/main.css
  faq.html
  index.html
Labels: hacktoberfest-accepted

#58 Updated the scroll bar
  dist/css/main.css
Labels: hacktoberfest-accepted

#62 Updated the 'about' section to some more relevant text.
  about.html
Labels: hacktoberfest-accepted

#70 Added Core-Team to About page
  about.html
  dist/css/achievements.css
Labels: hacktoberfest-accepted

#72 Update contributorsList.js
  contributors/contributorsList.js
Labels: hacktoberfest-accepted

#73 Added some links to pages where found missing
  about.html
  achievements.html
  contributors/contributorsList.js
  faq.html
  privacy_policy.html
  terms_of_use.html
Labels: hacktoberfest-accepted

#74 Improved Footer Design
  dist/css/main.css
  index.html
Labels: hacktoberfest-accepted

#76 Update about.html
  about.html
Labels: hacktoberfest-accepted

#77 Update terms_of_use.html
  terms_of_use.html
Labels: hacktoberfest-accepted

#79 FAQ, No code file
  Faqcontent
  about.html
Labels: hacktoberfest-accepted

#78 About section changed
  about.html
  dist/css/about.css
Labels: hacktoberfest-accepted

#80 Changed footer
  about.html
  achievements.html
  faq.html
  index.html
Labels: hacktoberfest-accepted

#81 footer changes
  achievements.html
Labels: hacktoberfest-accepted

#82 Update faq.html
  faq.html
Labels: hacktoberfest-accepted

#85 Update achievements.html
  achievements.html
Labels: hacktoberfest-accepted

#87 Update faq.html
  faq.html
Labels: hacktoberfest-accepted

#88 fixed css
  about.html
  achievements.html
  contributors/contributorsList.js
  dist/css/about.css
  dist/css/main.css
  dist/css/main.css.map
  dist/css/main.scss
  dist/css/style.css
  index.html
Labels: hacktoberfest-accepted

#93 Update index.html
  index.html
Labels: hacktoberfest-accepted

#95 Add Content to About us
  about.html
  contributors/contributorsList.js
Labels: hacktoberfest-accepted

#98 about page improvised
  about.html
Labels: hacktoberfest-accepted

#100 FIXED FOOTER ICONS
  achievements.html
  index.html
Labels: hacktoberfest-accepted

#101 Contact Page Created #89
  about.html
  achievements.html
  contactUs.html
  index.html
Labels: hacktoberfest-accepted

#106 Update achievements.html
  achievements.html
Labels: hacktoberfest-accepted

#102 added a back to top button
  dist/css/main.css
  dist/js/main.js
  index.html
Labels: hacktoberfest-accepted

#104 project page made
  about.html
  achievements.html
  assets/project (1).jpg
  assets/project (2).jpg
  assets/project (3).jpg
  dist/css/project.css
  faq.html
  index.html
  privacy_policy.html
  project.html
  terms_of_use.html
Labels: hacktoberfest-accepted

#105 Added the Objectives page
  .nojekyll
  Objectives.html
  index.html
  styles.css
Labels: hacktoberfest-accepted

#110 Update achievements.css
  dist/css/achievements.css
Labels: hacktoberfest-accepted

#111 Update achievements.html
  achievements.html
Labels: hacktoberfest-accepted

#112 Update index.html
  index.html
Labels: bug, hacktoberfest-accepted

#113 Added Navbar and footer in "our objectives" page
  Objectives.html
  styles.css
Labels: hacktoberfest-accepted

#114 Corrected footer position in project.index
  dist/css/project.css
  project.html
Labels: hacktoberfest-accepted

#115 Added the link to "Our Objectives" page in the navbar of all the remaining pages.
  about.html
  achievements.html
  contactUs.html
  faq.html
  privacy_policy.html
  project.html
  terms_of_use.html
Labels: hacktoberfest-accepted

#125 Update faq.html
  faq.html
Labels: hacktoberfest-accepted

#122 Footer Improved
  about.html
  achievements.html
  dist/css/about.css
  dist/css/achievements.css
  dist/css/faq.css
  dist/css/main.css
  faq.html
  index.css
  index.html
  privacy_policy.html
  project.css
  project.html
  terms_of_use.html
Labels: hacktoberfest-accepted

#123 Replaced the Logo's Font on Every Page
  dist/css/main.css
Labels: hacktoberfest-accepted

#118 project section improved
  project.css
  project.html
Labels: hacktoberfest-accepted

#128 Improved the whole Home Page
  index.css
  index.html
  project.css
  project.html
Labels: hacktoberfest-accepted

#132 Improved Navbar and Styling in all pages
  Objectives.html
  about.html
  achievements.html
  contactUs.html
  dist/css/about.css
  dist/css/achievements.css
  dist/css/faq.css
  dist/css/main.css
  dist/css/project.css
  index.css
  index.html
  project.css
  project.html
Labels: hacktoberfest-accepted

#126 To redesign Our Objective Page
  Objectives.html
Labels: hacktoberfest-accepted

#135 My changes
  about.html
  contributors/contributorsList.js
  dist/css/main.css
  index.html
Labels: hacktoberfest-accepted
